apiVersion: v1
kind: Pod
metadata:
  name: tweet-board-ms
  labels:
    app: tweet-board-ms
spec:
  nodeName: minikube
  containers:
  - name: tweet-board
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/devoxxUK18-active-ui-streaming-analysis"
    - name: APP_PORT
      value: "8104"
    - name: APP_HOME
      value: "web-app"
    - name: APP_STARTUP
      value: "app.js"
    - name: KAFKA_HOST
      value: "zookeeper.kafka"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "tweetsTopic"
    - name: REDIS_HOST
      value: "redis-cache"
    - name: REDIS_PORT
      value: "6379"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8104
