apiVersion: v1
kind: Pod
metadata:
  name: tweet-event-generator-ms
  labels:
    app: tweet-event-generator-ms
spec:
  nodeName: minikube
  containers:
  - name: tweet-event-generator
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/devoxxUK18-active-ui-streaming-analysis"
    - name: APP_PORT
      value: "8096"
    - name: APP_HOME
      value: "generate-tweet-events"
    - name: APP_STARTUP
      value: "index.js"
    - name: KAFKA_HOST
      value: "zookeeper.kafka"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "tweetsTopic"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8096
    
